/*==============================================================
Object Name : AEROSPACE_PARTS_TARGET
Purpose     : Target table storing deduplicated, transformed,
              and enriched aerospace parts inventory data with
              SCD Type 1 overwrite strategy. Includes derived
              columns RISK_SCORE, LOAD_TIMESTAMP, and
              LIFECYCLE_STATUS for reporting and compliance.
Generated By: SDLC_AGENT
Generated Date: 2025-07-14
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set session context to target database and schema
---------------------------------------------------------

USE DATABASE IDEA_2_DB;
USE SCHEMA PUBLIC;

---------------------------------------------------------
-- SECTION 2
-- Purpose: DDL - Create AEROSPACE_PARTS_TARGET table
--          if it does not already exist
---------------------------------------------------------

-- Create the primary target table for aerospace parts inventory
-- with all source columns, derived columns, and audit metadata
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER          VARCHAR(100)    NOT NULL COMMENT 'Business key - unique identifier for each aerospace part',
    PART_NAME            VARCHAR(255)    COMMENT 'Descriptive name of the aerospace part',
    MANUFACTURER         VARCHAR(255)    COMMENT 'Manufacturer name stored in CamelCase format (INITCAP applied)',
    CATEGORY             VARCHAR(100)    COMMENT 'Part category classification',
    CERTIFICATION_STATUS VARCHAR(50)     COMMENT 'Certification status: Pending, FAA, EASA, or Dual',
    LEAD_TIME_DAYS       NUMBER(10,0)    COMMENT 'Procurement lead time in days',
    WEIGHT_KG            NUMBER(18,4)    COMMENT 'Part weight in kilograms; NULL if source value was <= 0',
    UNIT_PRICE_USD       NUMBER(18,2)    COMMENT 'Unit price in USD rounded to 2 decimal places',
    INSTALLATION_DATE    DATE            COMMENT 'Date the part was installed',
    LIFECYCLE_STATUS     VARCHAR(50)     COMMENT 'Lifecycle status: Active, End of Life, Decommissioned, etc.',
    SUPPLIER_ID          VARCHAR(100)    COMMENT 'Identifier for the parts supplier',
    WAREHOUSE_LOCATION   VARCHAR(255)    COMMENT 'Physical warehouse location of the part',
    QUANTITY_ON_HAND     NUMBER(18,0)    COMMENT 'Current quantity available in inventory',
    LAST_INSPECTION_DATE DATE            COMMENT 'Date of the most recent inspection',
    UPDATED_AT           TIMESTAMP_NTZ   COMMENT 'Timestamp of last update in source system',
    RISK_SCORE           VARCHAR(20)     COMMENT 'Derived risk classification: High Risk, Medium Risk, or Low Risk',
    LOAD_TIMESTAMP       TIMESTAMP_NTZ   COMMENT 'Timestamp when the record was last loaded by the pipeline',
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)
);