/*==============================================================
Object Name : ETL_RECONCILIATION_LOG
Purpose     : Audit and reconciliation log table capturing
              pipeline execution metrics for every run of
              SP_LOAD_AEROSPACE_PARTS_SCD1. Mandatory for
              compliance, audit, and pipeline health monitoring.
Generated By: SDLC_AGENT
Generated Date: 2025-07-14
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set session context to target database and schema
---------------------------------------------------------

USE DATABASE IDEA_2_DB;
USE SCHEMA PUBLIC;

---------------------------------------------------------
-- SECTION 2
-- Purpose: DDL - Create ETL_RECONCILIATION_LOG table
--          if it does not already exist
---------------------------------------------------------

-- Create the reconciliation log table to capture per-execution
-- pipeline metrics including counts and pipeline status
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    LOG_ID           NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'Auto-generated unique log entry identifier',
    RUN_TIMESTAMP    TIMESTAMP_NTZ  NOT NULL COMMENT 'Timestamp when the pipeline run was initiated',
    SOURCE_COUNT     NUMBER(18,0)   COMMENT 'Total records extracted from source after incremental filter',
    TARGET_COUNT     NUMBER(18,0)   COMMENT 'Total records present in target after load completes',
    INSERTED_COUNT   NUMBER(18,0)   COMMENT 'Number of new records inserted during this run',
    UPDATED_COUNT    NUMBER(18,0)   COMMENT 'Number of existing records updated during this run',
    DELETED_COUNT    NUMBER(18,0)   COMMENT 'Number of records soft-deleted (Decommissioned) during this run',
    ERROR_COUNT      NUMBER(18,0)   COMMENT 'Number of records that encountered errors during processing',
    PIPELINE_STATUS  VARCHAR(20)    COMMENT 'Final pipeline status: SUCCESS or FAILED',
    ERROR_MESSAGE    VARCHAR(4000)  COMMENT 'Error message captured if pipeline status is FAILED'
);