/*==============================================================
Object Name : PIPELINE_CONTROL
Purpose     : Control table to track the last successful
              pipeline execution timestamp. Used to determine
              incremental load boundaries for
              SP_LOAD_AEROSPACE_PARTS_SCD1.
Generated By: SDLC_AGENT
Generated Date: 2025-07-14
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set session context to target database and schema
---------------------------------------------------------

USE DATABASE IDEA_2_DB;
USE SCHEMA PUBLIC;

---------------------------------------------------------
-- SECTION 2
-- Purpose: DDL - Create PIPELINE_CONTROL table
--          if it does not already exist
---------------------------------------------------------

-- Create the pipeline control table to persist the last
-- successful run timestamp for incremental load logic
CREATE TABLE IF NOT EXISTS PIPELINE_CONTROL (
    PIPELINE_NAME              VARCHAR(200)   NOT NULL COMMENT 'Unique name identifying the pipeline',
    LAST_SUCCESSFUL_RUN_TS     TIMESTAMP_NTZ  COMMENT 'Timestamp of the last successful pipeline execution; NULL triggers full load',
    UPDATED_AT                 TIMESTAMP_NTZ  COMMENT 'Timestamp when this control record was last updated',
    CONSTRAINT PK_PIPELINE_CONTROL PRIMARY KEY (PIPELINE_NAME)
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: DML - Seed the initial control record for
--          SP_LOAD_AEROSPACE_PARTS_SCD1 pipeline
---------------------------------------------------------

-- Insert the initial control row for the aerospace parts pipeline
-- LAST_SUCCESSFUL_RUN_TS is NULL to trigger a full load on first run
INSERT INTO PIPELINE_CONTROL (PIPELINE_NAME, LAST_SUCCESSFUL_RUN_TS, UPDATED_AT)
SELECT 'SP_LOAD_AEROSPACE_PARTS_SCD1', NULL, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
WHERE NOT EXISTS (
    SELECT 1 FROM PIPELINE_CONTROL
    WHERE PIPELINE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1'
);