/*==============================================================
Object Name : DDL_AEROSPACE_PARTS_TABLES
Purpose     : Creates all required tables for the Aerospace Parts
              inventory pipeline: source staging table, target SCD1
              table, pipeline control table, and ETL reconciliation
              log. Implements SCRUM-62 pipeline infrastructure.
Generated By: SDLC_AGENT
Generated Date: 2025-01-31
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Establish session context — target database and schema
---------------------------------------------------------

-- Set the active database for all subsequent statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema for all subsequent statements
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: DDL — Create AEROSPACE_PARTS_SOURCE staging table
--          This table receives raw inbound data from the upstream
--          aerospace parts inventory system before transformation.
---------------------------------------------------------

-- Create the source staging table if it does not already exist.
-- Stores raw aerospace parts data as received from the upstream system.
-- PART_NUMBER is the business key used for deduplication and SCD1 merge.
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_SOURCE (
    PART_NUMBER          VARCHAR(100)    NOT NULL COMMENT 'Unique business key identifying the aerospace part',
    PART_NAME            VARCHAR(255)    COMMENT 'Descriptive name of the aerospace part',
    MANUFACTURER         VARCHAR(255)    COMMENT 'Name of the manufacturer — will be CamelCase-transformed in target',
    CATEGORY             VARCHAR(100)    COMMENT 'Part category (e.g., Structural, Avionics, Propulsion)',
    WEIGHT_KG            NUMBER(10,4)    COMMENT 'Weight of the part in kilograms; values <= 0 are invalid',
    UNIT_PRICE_USD       NUMBER(18,6)    COMMENT 'Unit price in USD; will be rounded to 2 decimal places in target',
    LEAD_TIME_DAYS       NUMBER(6,0)     COMMENT 'Procurement lead time in days; used in RISK_SCORE derivation',
    CERTIFICATION_STATUS VARCHAR(50)     COMMENT 'Certification status: Pending, FAA, EASA, or Dual',
    LIFECYCLE_STATUS     VARCHAR(50)     COMMENT 'Lifecycle status: Active, End of Life, Decommissioned, etc.',
    INSTALLATION_DATE    DATE            COMMENT 'Date the part was installed; used in End-of-Life exclusion rule',
    SUPPLIER_ID          VARCHAR(100)    COMMENT 'Identifier of the supplying vendor',
    WAREHOUSE_LOCATION   VARCHAR(255)    COMMENT 'Physical warehouse location of the part',
    QUANTITY_ON_HAND     NUMBER(10,0)    COMMENT 'Current stock quantity available in warehouse',
    REORDER_THRESHOLD    NUMBER(10,0)    COMMENT 'Minimum quantity level that triggers a reorder',
    UPDATED_AT           TIMESTAMP_NTZ   COMMENT 'Timestamp of the last update in the source system; drives incremental load'
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: DDL — Create AEROSPACE_PARTS_TARGET table
--          This is the SCD Type 1 target table. Records are
--          upserted (overwritten) on PART_NUMBER match.
--          Includes all transformation-applied and derived columns.
---------------------------------------------------------

-- Create the SCD Type 1 target table if it does not already exist.
-- All transformation rules (CamelCase MANUFACTURER, NULL WEIGHT_KG,
-- rounded UNIT_PRICE_USD, RISK_SCORE derivation) are applied before
-- records land in this table. PART_NUMBER is the unique business key.
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER          VARCHAR(100)    NOT NULL COMMENT 'Unique business key — SCD1 merge key',
    PART_NAME            VARCHAR(255)    COMMENT 'Descriptive name of the aerospace part',
    MANUFACTURER         VARCHAR(255)    COMMENT 'CamelCase-transformed manufacturer name (e.g., Boeing Corp)',
    CATEGORY             VARCHAR(100)    COMMENT 'Part category classification',
    WEIGHT_KG            NUMBER(10,4)    COMMENT 'Weight in kg; NULL when source value was <= 0 (invalid)',
    UNIT_PRICE_USD       NUMBER(18,2)    COMMENT 'Unit price rounded to exactly 2 decimal places',
    LEAD_TIME_DAYS       NUMBER(6,0)     COMMENT 'Procurement lead time in days',
    CERTIFICATION_STATUS VARCHAR(50)     COMMENT 'Certification status: Pending, FAA, EASA, or Dual',
    LIFECYCLE_STATUS     VARCHAR(50)     COMMENT 'Current lifecycle status including Decommissioned for soft-deleted records',
    INSTALLATION_DATE    DATE            COMMENT 'Installation date of the part',
    SUPPLIER_ID          VARCHAR(100)    COMMENT 'Supplier vendor identifier',
    WAREHOUSE_LOCATION   VARCHAR(255)    COMMENT 'Physical warehouse location',
    QUANTITY_ON_HAND     NUMBER(10,0)    COMMENT 'Current stock quantity',
    REORDER_THRESHOLD    NUMBER(10,0)    COMMENT 'Reorder trigger threshold quantity',
    RISK_SCORE           VARCHAR(20)     COMMENT 'Derived risk classification: High Risk, Medium Risk, or Low Risk',
    UPDATED_AT           TIMESTAMP_NTZ   COMMENT 'Source system last-updated timestamp',
    PIPELINE_LOAD_TS     TIMESTAMP_NTZ   COMMENT 'Timestamp when this record was last written by the pipeline',
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: DDL — Create PIPELINE_CONTROL table
--          Stores the watermark (last successful run timestamp)
--          used to drive incremental load logic. One row per
--          pipeline name. First run detected when no row exists.
---------------------------------------------------------

-- Create the pipeline control/watermark table if it does not already exist.
-- The stored procedure reads LAST_SUCCESSFUL_RUN_TS to determine the
-- incremental window. On first run, no row exists and a full load is performed.
CREATE TABLE IF NOT EXISTS PIPELINE_CONTROL (
    PIPELINE_NAME            VARCHAR(200)    NOT NULL COMMENT 'Logical name of the pipeline (e.g., SP_LOAD_AEROSPACE_PARTS_SCD1)',
    LAST_SUCCESSFUL_RUN_TS   TIMESTAMP_NTZ   COMMENT 'Watermark: timestamp of the last successful pipeline execution',
    LAST_RUN_STATUS          VARCHAR(50)     COMMENT 'Status of the last run: SUCCESS or FAILED',
    LAST_RUN_TS              TIMESTAMP_NTZ   COMMENT 'Wall-clock timestamp of the last run attempt (success or failure)',
    CONSTRAINT PK_PIPELINE_CONTROL PRIMARY KEY (PIPELINE_NAME)
);

---------------------------------------------------------
-- SECTION 5
-- Purpose: DDL — Create ETL_RECONCILIATION_LOG table
--          Mandatory audit log. One row inserted per pipeline
--          execution capturing full metrics and status.
--          Required by compliance and architecture decisions.
---------------------------------------------------------

-- Create the ETL reconciliation log table if it does not already exist.
-- Every pipeline execution must insert exactly one row here regardless
-- of success or failure (AC-010, DEC-003).
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    LOG_ID               NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'Surrogate key auto-generated per log entry',
    PIPELINE_NAME        VARCHAR(200)    COMMENT 'Name of the pipeline that produced this log entry',
    RUN_TS               TIMESTAMP_NTZ   COMMENT 'Wall-clock timestamp when this pipeline run started',
    LOAD_TYPE            VARCHAR(20)     COMMENT 'FULL or INCREMENTAL — indicates which load mode was used',
    WATERMARK_USED       TIMESTAMP_NTZ   COMMENT 'The UPDATED_AT watermark applied for incremental filtering (NULL for full load)',
    SOURCE_COUNT         NUMBER(18,0)    COMMENT 'Total records read from source before exclusions',
    EXCLUDED_COUNT       NUMBER(18,0)    COMMENT 'Records excluded by End-of-Life + age rule (FR-006)',
    DEDUPLICATED_COUNT   NUMBER(18,0)    COMMENT 'Records after deduplication (latest UPDATED_AT per PART_NUMBER)',
    INSERTED_COUNT       NUMBER(18,0)    COMMENT 'Net new records inserted into target',
    UPDATED_COUNT        NUMBER(18,0)    COMMENT 'Existing records updated (SCD1 overwrite) in target',
    DELETED_COUNT        NUMBER(18,0)    COMMENT 'Records soft-deleted (marked Decommissioned) in target',
    TARGET_COUNT         NUMBER(18,0)    COMMENT 'Total active (non-Decommissioned) records in target after load',
    PIPELINE_STATUS      VARCHAR(20)     COMMENT 'Overall run status: SUCCESS or FAILED',
    ERROR_MESSAGE        VARCHAR(4000)   COMMENT 'Error detail if PIPELINE_STATUS = FAILED; NULL on success',
    JIRA_ISSUE           VARCHAR(50)     DEFAULT 'SCRUM-62' COMMENT 'Jira issue key for traceability'
);