/*==============================================================
Object Name    : 01_create_tables.sql
Purpose        : Create all base tables for the Aerospace Parts
                 Inventory pipeline including source, target,
                 staging, reconciliation log, error log, and
                 pipeline metadata tables.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create the source table AEROSPACE_PARTS_SOURCE
---------------------------------------------------------

-- Create AEROSPACE_PARTS_SOURCE table
-- Purpose: Holds raw aerospace parts inventory data ingested from upstream systems
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    PART_NAME               VARCHAR(500),
    MANUFACTURER            VARCHAR(500),
    WEIGHT_KG               NUMBER(18,4),
    UNIT_PRICE_USD          NUMBER(18,4),
    CERTIFICATION_STATUS    VARCHAR(100),
    LEAD_TIME_DAYS          NUMBER(10,0),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    QUANTITY_ON_HAND        NUMBER(10,0),
    WAREHOUSE_LOCATION      VARCHAR(200),
    SUPPLIER_CODE           VARCHAR(100),
    COUNTRY_OF_ORIGIN       VARCHAR(200),
    UPDATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create the target table AEROSPACE_PARTS_TARGET
---------------------------------------------------------

-- Create AEROSPACE_PARTS_TARGET table
-- Purpose: Final production table for aerospace parts inventory used for reporting,
--          compliance, procurement analysis, and operations
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    PART_NAME               VARCHAR(500),
    MANUFACTURER            VARCHAR(500),
    WEIGHT_KG               NUMBER(18,4),
    UNIT_PRICE_USD          NUMBER(18,2),
    CERTIFICATION_STATUS    VARCHAR(100),
    LEAD_TIME_DAYS          NUMBER(10,0),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    QUANTITY_ON_HAND        NUMBER(10,0),
    WAREHOUSE_LOCATION      VARCHAR(200),
    SUPPLIER_CODE           VARCHAR(100),
    COUNTRY_OF_ORIGIN       VARCHAR(200),
    RISK_SCORE              NUMBER(5,2),
    UPDATED_AT              TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    TARGET_LOADED_AT        TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED              BOOLEAN         DEFAULT FALSE,
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: Create the staging table for transformation processing
---------------------------------------------------------

-- Create AEROSPACE_PARTS_STAGING table
-- Purpose: Temporary staging table to hold transformed and validated data
--          before merging into the target table
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    PART_NAME               VARCHAR(500),
    MANUFACTURER            VARCHAR(500),
    WEIGHT_KG               NUMBER(18,4),
    UNIT_PRICE_USD          NUMBER(18,2),
    CERTIFICATION_STATUS    VARCHAR(100),
    LEAD_TIME_DAYS          NUMBER(10,0),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    QUANTITY_ON_HAND        NUMBER(10,0),
    WAREHOUSE_LOCATION      VARCHAR(200),
    SUPPLIER_CODE           VARCHAR(100),
    COUNTRY_OF_ORIGIN       VARCHAR(200),
    RISK_SCORE              NUMBER(5,2),
    UPDATED_AT              TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: Create the pipeline metadata table for incremental extraction
---------------------------------------------------------

-- Create PIPELINE_METADATA table
-- Purpose: Tracks the last successful execution timestamp to support
--          incremental extraction from AEROSPACE_PARTS_SOURCE (FR-005)
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.PIPELINE_METADATA (
    PIPELINE_NAME           VARCHAR(200)    NOT NULL,
    LAST_SUCCESSFUL_RUN_AT  TIMESTAMP_NTZ,
    LAST_RUN_STATUS         VARCHAR(50),
    LAST_RUN_MESSAGE        VARCHAR(2000),
    UPDATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PIPELINE_METADATA PRIMARY KEY (PIPELINE_NAME)
);

---------------------------------------------------------
-- SECTION 5
-- Purpose: Create the reconciliation log table
---------------------------------------------------------

-- Create ETL_RECONCILIATION_LOG table
-- Purpose: Stores reconciliation records for each pipeline run including
--          source/target counts, insert/update/delete counts, and status (FR-006)
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
    LOG_ID                  NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_TIMESTAMP           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_NAME           VARCHAR(200),
    SOURCE_RECORD_COUNT     NUMBER(18,0),
    TARGET_RECORD_COUNT     NUMBER(18,0),
    RECORDS_INSERTED        NUMBER(18,0),
    RECORDS_UPDATED         NUMBER(18,0),
    RECORDS_SOFT_DELETED    NUMBER(18,0),
    RECONCILIATION_STATUS   VARCHAR(10),
    NOTES                   VARCHAR(4000),
    CONSTRAINT PK_ETL_RECONCILIATION_LOG PRIMARY KEY (LOG_ID)
);

---------------------------------------------------------
-- SECTION 6
-- Purpose: Create the error log table
---------------------------------------------------------

-- Create ETL_ERROR_LOG table
-- Purpose: Captures and logs errors encountered during pipeline execution
--          for troubleshooting and notification purposes
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ETL_ERROR_LOG (
    ERROR_ID                NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ERROR_TIMESTAMP         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_NAME           VARCHAR(200),
    STEP_NAME               VARCHAR(200),
    ERROR_CODE              VARCHAR(100),
    ERROR_MESSAGE           VARCHAR(4000),
    ERROR_DETAIL            VARCHAR(4000),
    CONSTRAINT PK_ETL_ERROR_LOG PRIMARY KEY (ERROR_ID)
);

---------------------------------------------------------
-- SECTION 7
-- Purpose: Seed initial pipeline metadata record
---------------------------------------------------------

-- Insert initial pipeline metadata record if not exists
-- Purpose: Seeds the PIPELINE_METADATA table with the initial record for the
--          aerospace parts pipeline so incremental extraction can begin
MERGE INTO IDEA_2_DB.PUBLIC.PIPELINE_METADATA AS TGT
USING (
    SELECT
        'AEROSPACE_PARTS_PIPELINE' AS PIPELINE_NAME,
        '1900-01-01 00:00:00'::TIMESTAMP_NTZ AS LAST_SUCCESSFUL_RUN_AT,
        'INITIALIZED' AS LAST_RUN_STATUS,
        'Initial seed record' AS LAST_RUN_MESSAGE,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS UPDATED_AT
) AS SRC
ON TGT.PIPELINE_NAME = SRC.PIPELINE_NAME
WHEN NOT MATCHED THEN
    INSERT (PIPELINE_NAME, LAST_SUCCESSFUL_RUN_AT, LAST_RUN_STATUS, LAST_RUN_MESSAGE, UPDATED_AT)
    VALUES (SRC.PIPELINE_NAME, SRC.LAST_SUCCESSFUL_RUN_AT, SRC.LAST_RUN_STATUS, SRC.LAST_RUN_MESSAGE, SRC.UPDATED_AT);