/*==============================================================
Object Name    : 02_create_streams_and_metadata.sql
Purpose        : Create Snowflake stream on the source table to
                 capture CDC (Change Data Capture) for incremental
                 processing support.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create stream on source table for change tracking
---------------------------------------------------------

-- Create stream on AEROSPACE_PARTS_SOURCE
-- Purpose: Captures inserts, updates, and deletes on the source table
--          to enable incremental extraction for the pipeline (FR-005)
CREATE STREAM IF NOT EXISTS IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE_STREAM
    ON TABLE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;