/*==============================================================
Object Name    : 03_staging_load.sql
Purpose        : Truncate staging table and load incremental data
                 from AEROSPACE_PARTS_SOURCE into
                 AEROSPACE_PARTS_STAGING with all transformations
                 applied (FR-001 through FR-003, FR-007, FR-008).
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Clear staging table for fresh load
---------------------------------------------------------

-- Truncate the staging table
-- Purpose: Ensures staging table is empty before loading the current batch
--          to prevent duplicate or stale data from prior runs
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Load transformed incremental data into staging
--          applying FR-001, FR-002, FR-003, FR-007, FR-008
---------------------------------------------------------

-- Insert transformed source data into staging table
-- Purpose: Extracts records from AEROSPACE_PARTS_SOURCE that have been updated
--          since the last successful pipeline run (FR-005 incremental extraction),
--          applies CamelCase manufacturer conversion (FR-001),
--          replaces invalid weight values with NULL (FR-002),
--          rounds unit price to 2 decimals (FR-003),
--          computes risk score based on certification and lead time (FR-007),
--          filters out End of Life records older than 3 years (FR-008),
--          and deduplicates by PART_NUMBER keeping the latest record
INSERT INTO IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING (
    PART_NUMBER,
    PART_NAME,
    MANUFACTURER,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    QUANTITY_ON_HAND,
    WAREHOUSE_LOCATION,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    RISK_SCORE,
    UPDATED_AT,
    CREATED_AT
)
SELECT
    SRC.PART_NUMBER,
    SRC.PART_NAME,

    -- FR-001: Convert MANUFACTURER to CamelCase
    -- Each word's first letter is capitalized, remaining letters are lowercase
    INITCAP(TRIM(SRC.MANUFACTURER)) AS MANUFACTURER,

    -- FR-002: Replace WEIGHT_KG <= 0 with NULL
    CASE
        WHEN SRC.WEIGHT_KG <= 0 THEN NULL
        ELSE SRC.WEIGHT_KG
    END AS WEIGHT_KG,

    -- FR-003: Round UNIT_PRICE_USD to 2 decimal places
    ROUND(SRC.UNIT_PRICE_USD, 2) AS UNIT_PRICE_USD,

    SRC.CERTIFICATION_STATUS,
    SRC.LEAD_TIME_DAYS,
    SRC.LIFECYCLE_STATUS,
    SRC.INSTALLATION_DATE,
    SRC.QUANTITY_ON_HAND,
    SRC.WAREHOUSE_LOCATION,
    SRC.SUPPLIER_CODE,
    SRC.COUNTRY_OF_ORIGIN,

    -- FR-007: Compute RISK_SCORE based on CERTIFICATION_STATUS and LEAD_TIME_DAYS
    -- High risk (10): Expired certification with long lead time (>90 days)
    -- Medium-high risk (7): Expired certification with moderate lead time
    -- Medium risk (5): Pending certification with long lead time (>90 days)
    -- Low-medium risk (3): Pending certification with moderate lead time
    -- Low risk (1): Certified parts
    CASE
        WHEN SRC.CERTIFICATION_STATUS = 'Expired' AND SRC.LEAD_TIME_DAYS > 90 THEN 10.00
        WHEN SRC.CERTIFICATION_STATUS = 'Expired' AND SRC.LEAD_TIME_DAYS <= 90 THEN 7.00
        WHEN SRC.CERTIFICATION_STATUS = 'Pending' AND SRC.LEAD_TIME_DAYS > 90 THEN 5.00
        WHEN SRC.CERTIFICATION_STATUS = 'Pending' AND SRC.LEAD_TIME_DAYS <= 90 THEN 3.00
        WHEN SRC.CERTIFICATION_STATUS = 'Certified' THEN 1.00
        ELSE 5.00
    END AS RISK_SCORE,

    SRC.UPDATED_AT,
    SRC.CREATED_AT

FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE SRC
INNER JOIN IDEA_2_DB.PUBLIC.PIPELINE_METADATA PM
    ON PM.PIPELINE_NAME = 'AEROSPACE_PARTS_PIPELINE'

WHERE
    -- FR-005: Incremental extraction using UPDATED_AT
    SRC.UPDATED_AT > PM.LAST_SUCCESSFUL_RUN_AT

    -- FR-008: Filter out End of Life records with INSTALLATION_DATE older than 3 years
    AND NOT (
        SRC.LIFECYCLE_STATUS = 'End of Life'
        AND SRC.INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
    )

-- Dedup: Keep only the latest record per PART_NUMBER
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SRC.PART_NUMBER
    ORDER BY SRC.UPDATED_AT DESC
) = 1;