/*==============================================================
Object Name    : 04_transform_and_validate.sql
Purpose        : Validate the transformed data in the staging table
                 against business rules and data quality checks.
                 Log any validation errors to the error log table.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log records with NULL PART_NUMBER (critical validation)
---------------------------------------------------------

-- Insert validation errors for NULL PART_NUMBER records
-- Purpose: PART_NUMBER is the primary key and merge key; NULL values
--          would cause merge failures and data integrity issues
INSERT INTO IDEA_2_DB.PUBLIC.ETL_ERROR_LOG (
    ERROR_TIMESTAMP,
    PIPELINE_NAME,
    STEP_NAME,
    ERROR_CODE,
    ERROR_MESSAGE,
    ERROR_DETAIL
)
SELECT
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
    'AEROSPACE_PARTS_PIPELINE',
    'VALIDATION',
    'VAL_001',
    'NULL PART_NUMBER detected in staging',
    'PART_NAME: ' || COALESCE(PART_NAME, 'N/A') || ', MANUFACTURER: ' || COALESCE(MANUFACTURER, 'N/A')
FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING
WHERE PART_NUMBER IS NULL;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Remove invalid records from staging before merge
---------------------------------------------------------

-- Delete records with NULL PART_NUMBER from staging
-- Purpose: Prevents invalid records from being merged into the target table;
--          these records have already been logged to the error log
DELETE FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING
WHERE PART_NUMBER IS NULL;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Log records with negative UNIT_PRICE_USD
---------------------------------------------------------

-- Insert validation errors for negative UNIT_PRICE_USD records
-- Purpose: Negative prices are likely data entry errors and should be flagged
--          for review by the data quality team
INSERT INTO IDEA_2_DB.PUBLIC.ETL_ERROR_LOG (
    ERROR_TIMESTAMP,
    PIPELINE_NAME,
    STEP_NAME,
    ERROR_CODE,
    ERROR_MESSAGE,
    ERROR_DETAIL
)
SELECT
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
    'AEROSPACE_PARTS_PIPELINE',
    'VALIDATION',
    'VAL_002',
    'Negative UNIT_PRICE_USD detected in staging',
    'PART_NUMBER: ' || PART_NUMBER || ', UNIT_PRICE_USD: ' || CAST(UNIT_PRICE_USD AS VARCHAR)
FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING
WHERE UNIT_PRICE_USD < 0;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Log records with invalid CERTIFICATION_STATUS values
---------------------------------------------------------

-- Insert validation errors for unexpected CERTIFICATION_STATUS values
-- Purpose: Ensures only known certification statuses are loaded into the target
--          to maintain data consistency for compliance reporting
INSERT INTO IDEA_2_DB.PUBLIC.ETL_ERROR_LOG (
    ERROR_TIMESTAMP,
    PIPELINE_NAME,
    STEP_NAME,
    ERROR_CODE,
    ERROR_MESSAGE,
    ERROR_DETAIL
)
SELECT
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
    'AEROSPACE_PARTS_PIPELINE',
    'VALIDATION',
    'VAL_003',
    'Unknown CERTIFICATION_STATUS detected in staging',
    'PART_NUMBER: ' || PART_NUMBER || ', CERTIFICATION_STATUS: ' || COALESCE(CERTIFICATION_STATUS, 'NULL')
FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING
WHERE CERTIFICATION_STATUS NOT IN ('Certified', 'Pending', 'Expired')
  AND CERTIFICATION_STATUS IS NOT NULL;