/*==============================================================
Object Name    : 05_merge_to_target.sql
Purpose        : Perform SCD Type 1 MERGE from staging into the
                 target table AEROSPACE_PARTS_TARGET using
                 PART_NUMBER as the join key (FR-004).
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: SCD Type 1 Merge - Upsert staging data into target (FR-004)
---------------------------------------------------------

-- Merge staging data into AEROSPACE_PARTS_TARGET
-- Purpose: Implements SCD Type 1 upsert logic using PART_NUMBER as the join key.
--          When a matching PART_NUMBER is found in the target, all columns are
--          updated with the latest source values. When no match is found, a new
--          record is inserted. This ensures the target always reflects the most
--          current state of each aerospace part (FR-004).
MERGE INTO IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET AS TGT
USING IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING AS STG
ON TGT.PART_NUMBER = STG.PART_NUMBER

WHEN MATCHED THEN
    UPDATE SET
        TGT.PART_NAME              = STG.PART_NAME,
        TGT.MANUFACTURER           = STG.MANUFACTURER,
        TGT.WEIGHT_KG              = STG.WEIGHT_KG,
        TGT.UNIT_PRICE_USD         = STG.UNIT_PRICE_USD,
        TGT.CERTIFICATION_STATUS   = STG.CERTIFICATION_STATUS,
        TGT.LEAD_TIME_DAYS         = STG.LEAD_TIME_DAYS,
        TGT.LIFECYCLE_STATUS       = STG.LIFECYCLE_STATUS,
        TGT.INSTALLATION_DATE      = STG.INSTALLATION_DATE,
        TGT.QUANTITY_ON_HAND       = STG.QUANTITY_ON_HAND,
        TGT.WAREHOUSE_LOCATION     = STG.WAREHOUSE_LOCATION,
        TGT.SUPPLIER_CODE          = STG.SUPPLIER_CODE,
        TGT.COUNTRY_OF_ORIGIN      = STG.COUNTRY_OF_ORIGIN,
        TGT.RISK_SCORE             = STG.RISK_SCORE,
        TGT.UPDATED_AT             = STG.UPDATED_AT,
        TGT.TARGET_LOADED_AT       = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        TGT.IS_DELETED             = FALSE

WHEN NOT MATCHED THEN
    INSERT (
        PART_NUMBER,
        PART_NAME,
        MANUFACTURER,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        QUANTITY_ON_HAND,
        WAREHOUSE_LOCATION,
        SUPPLIER_CODE,
        COUNTRY_OF_ORIGIN,
        RISK_SCORE,
        UPDATED_AT,
        CREATED_AT,
        TARGET_LOADED_AT,
        IS_DELETED
    )
    VALUES (
        STG.PART_NUMBER,
        STG.PART_NAME,
        STG.MANUFACTURER,
        STG.WEIGHT_KG,
        STG.UNIT_PRICE_USD,
        STG.CERTIFICATION_STATUS,
        STG.LEAD_TIME_DAYS,
        STG.LIFECYCLE_STATUS,
        STG.INSTALLATION_DATE,
        STG.QUANTITY_ON_HAND,
        STG.WAREHOUSE_LOCATION,
        STG.SUPPLIER_CODE,
        STG.COUNTRY_OF_ORIGIN,
        STG.RISK_SCORE,
        STG.UPDATED_AT,
        STG.CREATED_AT,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        FALSE
    );