/*==============================================================
Object Name    : 06_soft_delete.sql
Purpose        : Implement soft delete logic (FR-009) to mark
                 target records as Decommissioned when their
                 PART_NUMBER is not present in the current
                 source extraction batch.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Soft delete target records not in current batch (FR-009)
---------------------------------------------------------

-- Update LIFECYCLE_STATUS to Decommissioned for missing parts
-- Purpose: Implements FR-009 soft delete logic. Target records whose PART_NUMBER
--          does not appear in the current staging batch (i.e., the current source
--          extraction) are marked as Decommissioned and flagged as soft-deleted.
--          This ensures that parts no longer supplied are properly tracked for
--          compliance and procurement analysis without physically removing data.
UPDATE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET
SET
    LIFECYCLE_STATUS = 'Decommissioned',
    IS_DELETED = TRUE,
    TARGET_LOADED_AT = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
WHERE PART_NUMBER NOT IN (
    SELECT PART_NUMBER
    FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING
)
AND IS_DELETED = FALSE;