/*==============================================================
Object Name    : 07_reconciliation_logging.sql
Purpose        : Insert reconciliation records into
                 ETL_RECONCILIATION_LOG with run metrics
                 including source count, target count, inserts,
                 updates, soft deletes, and status (FR-006).
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log reconciliation metrics for the current pipeline run (FR-006)
---------------------------------------------------------

-- Insert reconciliation record into ETL_RECONCILIATION_LOG
-- Purpose: Captures comprehensive pipeline execution metrics including:
--          - Source record count (records in staging after transformation)
--          - Target record count (total active records in target)
--          - Records inserted (new parts added)
--          - Records updated (existing parts refreshed via SCD Type 1)
--          - Records soft-deleted (parts marked as Decommissioned)
--          - Reconciliation status (PASS if source count matches inserts + updates, FAIL otherwise)
--          This supports FR-006 reconciliation logging requirements.
INSERT INTO IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
    RUN_TIMESTAMP,
    PIPELINE_NAME,
    SOURCE_RECORD_COUNT,
    TARGET_RECORD_COUNT,
    RECORDS_INSERTED,
    RECORDS_UPDATED,
    RECORDS_SOFT_DELETED,
    RECONCILIATION_STATUS,
    NOTES
)
SELECT
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ                          AS RUN_TIMESTAMP,
    'AEROSPACE_PARTS_PIPELINE'                                  AS PIPELINE_NAME,

    -- Source record count: total records in staging batch
    (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING)
                                                                AS SOURCE_RECORD_COUNT,

    -- Target record count: total active (non-deleted) records in target
    (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET WHERE IS_DELETED = FALSE)
                                                                AS TARGET_RECORD_COUNT,

    -- Records inserted: target records created during this load cycle
    -- (created_at matches target_loaded_at within a small window, and no prior existence)
    (SELECT COUNT(*)
     FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET TGT
     INNER JOIN IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING STG
         ON TGT.PART_NUMBER = STG.PART_NUMBER
     WHERE TGT.CREATED_AT = TGT.TARGET_LOADED_AT)
                                                                AS RECORDS_INSERTED,

    -- Records updated: target records that existed before and were updated
    (SELECT COUNT(*)
     FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET TGT
     INNER JOIN IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING STG
         ON TGT.PART_NUMBER = STG.PART_NUMBER
     WHERE TGT.CREATED_AT <> TGT.TARGET_LOADED_AT)
                                                                AS RECORDS_UPDATED,

    -- Records soft-deleted: target records marked as Decommissioned and IS_DELETED = TRUE
    (SELECT COUNT(*)
     FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET
     WHERE IS_DELETED = TRUE
       AND LIFECYCLE_STATUS = 'Decommissioned'
       AND TARGET_LOADED_AT >= CURRENT_TIMESTAMP()::TIMESTAMP_NTZ - INTERVAL '1 HOUR')
                                                                AS RECORDS_SOFT_DELETED,

    -- Reconciliation status: PASS if source count equals inserts + updates
    CASE
        WHEN (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING) =
             (
                 (SELECT COUNT(*)
                  FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET TGT
                  INNER JOIN IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING STG
                      ON TGT.PART_NUMBER = STG.PART_NUMBER
                  WHERE TGT.CREATED_AT = TGT.TARGET_LOADED_AT)
                 +
                 (SELECT COUNT(*)
                  FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET TGT
                  INNER JOIN IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_STAGING STG
                      ON TGT.PART_NUMBER = STG.PART_NUMBER
                  WHERE TGT.CREATED_AT <> TGT.TARGET_LOADED_AT)
             )
        THEN 'PASS'
        ELSE 'FAIL'
    END                                                         AS RECONCILIATION_STATUS,

    'Pipeline run completed at ' || CURRENT_TIMESTAMP()::VARCHAR AS NOTES;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Update pipeline metadata with last successful run timestamp (FR-005)
---------------------------------------------------------

-- Update PIPELINE_METADATA with current run timestamp
-- Purpose: Records the current timestamp as the last successful execution time
--          so the next incremental extraction (FR-005) only picks up records
--          modified after this point
UPDATE IDEA_2_DB.PUBLIC.PIPELINE_METADATA
SET
    LAST_SUCCESSFUL_RUN_AT = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
    LAST_RUN_STATUS = 'SUCCESS',
    LAST_RUN_MESSAGE = 'Pipeline completed successfully',
    UPDATED_AT = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
WHERE PIPELINE_NAME = 'AEROSPACE_PARTS_PIPELINE';