/*==============================================================
Object Name    : 08_create_tasks.sql
Purpose        : Create Snowflake tasks to orchestrate the
                 aerospace parts pipeline with daily scheduling
                 at 02:00 UTC as specified in the TRD.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-15
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create root task for staging load (runs daily at 02:00 UTC)
---------------------------------------------------------

-- Create task AEROSPACE_PARTS_TASK_01_STAGING_LOAD
-- Purpose: Root task that triggers daily at 02:00 UTC to truncate the staging
--          table and load transformed incremental data from source (FR-001 to FR-008)
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TASK_01_STAGING_LOAD
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    COMMENT = 'Root task: Load incremental transformed data into staging table daily at 02:00 UTC'
AS
CALL IDEA_2_DB.PUBLIC.SP_AEROSPACE_PARTS_PIPELINE();

---------------------------------------------------------
-- SECTION 2
-- Purpose: Resume the root task to activate the schedule
---------------------------------------------------------

-- Resume the root task
-- Purpose: Tasks are created in suspended state by default; this activates
--          the daily 02:00 UTC schedule for the pipeline
ALTER TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TASK_01_STAGING_LOAD RESUME;